= SlideshowFX developer documentation
:numbered:
:icons:

== Introduction

SlideshowFX is an application allowing you to create HTML5 based presentation in a very common manner. Nowadays we all use PowerPoint, Keynote and their friends but with evolution of web technologies, new perspectives are now possible. Indeed there is a lot of HTML5/JavaScript based framework, like http://lab.hakim.se/reveal-js/[reveal.js] or https://github.com/bartaz/impress.js/[impress.js], that allow you to create beautiful presentations to keep your audience active. It brings you a lot of freedom like adding a YouTube video right inside your presentation, playing music, automatically syntax highlighting code example and more. But to do such presentations you have to know HTML, CSS and JavaScript programming languages.

SlideshowFX lets programming languages to developers and presentations' creation to end users. This means that you will be able to create your presentations without knowing HTML, even if it is recommended to have the basics.

But SlideshowFX isn't just another simple presentation engine. It brings much more for you:

- A chat is provided so your audience can send you questions using their smartphones and you will answer them whenever you want ;
- A quiz creator so your audience can answer your quiz using their smartphones and you see results live ;
- Present using your hands by changing slides with two fingers, have a "laser" pointer by using one finger. It's cool isn't it? All of this brought to you by LeapMotion.
- Save your presentations on Dropbox or Google Drive ;
- Insert code snippets that can be executed directly from the presentation and console's output is displayed in the slide.

== Developer guide

=== Tools & APIs

[options=header, width="65"]
|===
| API, Tool | Version | Comments

| Java / JavaFX | {javafx-version} |

| asciidoctorj | {asciidoctorj-version} |

| Apache Felix | {apache-felix-version} |

| FontAwesomeFX | {fontawesomefx-version} |

| freemarker | {freemarker-version} |

| jsoup | {jsoup-version} |

| LeapMotion SDK | {leapmotion-sdk-version} |

| org.eclipse.mylyn.wikitext.core | {wikitext-core-version} | Library used for textile support

| org.eclipse.mylyn.wikitext.textile.core | {wikitext-textile-core-version} | Library used for textile support

| twitter4j | {twitter4j-version} |

| txtmark | {txtmark-version} | Library used for the markdown support

| vertx-core | {vertx-version} |

| zxing-core | {zxing-core-version} |

| zxing-jse | {zxing-jse-version} |

| http://ace.c9.io[ACE] | {ace-version} |

|===

=== Project structure

SlideshowFX contains the following modules:

- *SlideshowFX-app* which is the module for the desktop client of SlideshowFX ;
- *SlideshowFX-utils* which defines utilities classes that may be used in other modules ;
- *SlideshowFX-engines* which defines the engines that are used in SlideshowFX for working with templates and presentations ;
- *SlideshowFX-controls* which defines the custom graphical controls that may be used in other modules ;
- *SlideshowFX-global-configuration* which defines the classes allowing to access and interact the SlideshowFX configuration ;
- *SlideshowFX-logs* which defines the classes for the logging ;
- *SlideshowFX-osgi* which defines the OSGi classes that are useful for other modules ;
- *SlideshowFX-server* which defines a server that is used by SlideshowFX ;
- *SlideshowFX-markup* which defines the base classes for creating an OSGi module for supporting a new markup syntax in SlideshowFX to define slides' content ;
- *SlideshowFX-asciidoctor* which defines the implementation of SlideshowFX-markup to define slides' content in asciidoctor ;
- *SlideshowFX-html* which defines the implementation of SlideshowFX-markup to define slides' content in HTML ;
- *SlideshowFX-markdown* which defines the implementation of SlideshowFX-markup to define slides' content in markdown ;
- *SlideshowFX-textile* which defines the implementation of SlideshowFX-markup to define slides' content in textile ;
- *SlideshowFX-content-extension* which defines the base classes for creating an OSGi module for inserting specific content in slides (like images, ...) ;
- *SlideshowFX-alert-extension* which defines the implementation of SlideshowFX-content-extension to insert beautiful alerts in slides ;
- *SlideshowFX-code-extension* which defines the implementation of SlideshowFX-content-extension to insert code in slides ;
- *SlideshowFX-image-extension* which defines the implementation of SlideshowFX-content-extension to insert images in slides ;
- *SlideshowFX-link-extension* which defines the implementation of SlideshowFX-content-extension to insert HTML links in slides ;
- *SlideshowFX-quiz-extension* which defines the implementation of SlideshowFX-content-extension to insert quiz in slides ;
- *SlideshowFX-quote-extension* which defines the implementation of SlideshowFX-content-extension to insert quotes in slides ;
- *SlideshowFX-sequence-diagram-extension* which defines the implementation of SlideshowFX-content-extension to insert sequence diagrams in slides ;
- *SlideshowFX-snippet-extension* which defines the implementation of SlideshowFX-content-extension to insert executable code snippet in slides ;
- *SlideshowFX-hosting-connector* which defines the base classes for creating an OSGi module for connecting to a file hosting service ;
- *SlideshowFX-box-hosting-connector* which defines the implementation of SlideshowFX-hosting-connector to connect to Box ;
- *SlideshowFX-dropbox-hosting-connector* which defines the implementation of SlideshowFX-hosting-connector to connect to Dropbox ;
- *SlideshowFX-drive-hosting-connector* which defines the implementation of SlideshowFX-hosting-connector to connect to Google Drive ;
- *SlideshowFX-snippet-executor* which defines the base classes for creating an OSGi module for executing code snippet in a presentation ;
- *SlideshowFX-go-executor* which defines the base classes for creating an OSGi module for executing Go code snippet in a presentation ;
- *SlideshowFX-golo-executor* which defines the base classes for creating an OSGi module for executing Golo code snippet in a presentation ;
- *SlideshowFX-groovy-executor* which defines the base classes for creating an OSGi module for executing Groovy code snippet in a presentation ;
- *SlideshowFX-java-executor* which defines the base classes for creating an OSGi module for executing Java code snippet in a presentation ;
- *SlideshowFX-javascript-executor* which defines the base classes for creating an OSGi module for executing JavaScript code snippet in a presentation ;
- *SlideshowFX-kotlin-executor* which defines the base classes for creating an OSGi module for executing Kotlin code snippet in a presentation ;
- *SlideshowFX-scala-executor* which defines the base classes for creating an OSGi module for executing Scala code snippet in a presentation ;

=== Gradle

SlideshowFX uses http://www.gradle.org/[gradle] as build system. The version used is {gradle-version}. +
The following plugins are currently used in the Gradle script:

- bintray
- java
- asciidoctor

==== Tasks

In order to build SlideshowFX, some gradle tasks have been created:

- `buildJavaFXBundle` which depends on the JAR task has been created in the `SlideshowFX-app` project. This task creates the JavaFX bundle ;
- `installMarkupPlugins` (in the root project) which copies the markup supported to the directory of plugins ;
- `installContentExtensionPlugins` (in the root project) which copies the content extensions to the directory of plugins ;
- `installHostingConnectorPlugins` (in the root project) which copies the hosting connectors to the directory of plugins ;
- `installSnippetExecutor` (in the root project) which copies the snippet executors to the directory of plugins ;
- `installAllPlugins` (in the root project) which copies all plugins to the directory of plugins ;
- `packageSlideshowFX` (in the root project) which packages the application, markups, extensions and documentation together.

=== Set up your environment

==== Environment variable

In order to build SlideshowFX, you will need to set *JAVA_HOME* to point to your JDK {jdk-version} installation and *GRADLE_HOME* to your gradle installation. Ensure both variables are present in the *PATH* environment variable.

==== Running SlideshowFX in your IDE

If you are contributing to SlideshowFX and developing some features, you probably use an IDE (http://www.jetbrains.com/idea/[IntelliJ IDEA], https://netbeans.org/[NetBeans], http://www.eclipse.org/[eclipse], ...). +
Because SlideshowFX uses LeapMotion, you have to set up a JVM argument which is 
[source]
-Djava.library.path=./lib/Leap/<platform>

Values for the platform are:

- *osx*
- *windows_x86*
- *windows_x64*
- *linux_x86*
- *linux_x64*

If you want SlideshowFX manage and look where LeapMotion native libraries are located, instead of defining the `-Djava.library.path` JVM argument you can define the two following:
[source]
-Ddynamic.java.library.path=true -Dproject.stage=development

By doing so, SlideshowFX will automatically be looking for the folder `./lib/Leap/<platform>`.

=== Templates

Each presentation done with SlideshowFX is based on a _template_.  +
A template is composed by three main parts:

- A _template configuration_ file which contains the configuration of the template. This file *must be* named *template-config.json* and is written using JSON ;
- A _template file_ which is the HTML page that will host all slides of the presentation ;
- _Slide's template files_ which are the template for each kind of slide the user can add in his presentation.

All of this content is archived in a file with the extension *.sfxt* (which stands for SlideshowFX template)

A typical template archive structure is the following:
[source]
----
/
|- [F] template-config.json
|- [F] template.html
|- [D] resources
|- [D] slides
|------|- [D] template
----

Where:

- *[F]* = file
- *[D]* = directory

==== Template configuration file

The template configuration must be at the root of the archive and will contain all the configuration the template will need to load. An example is show below:
[source]
----
{
  "template" : {
    "name": "My first template",
    "file" : "template.html",
    "js-object" : "sfx",
    "resources-directory" : "resources",

    "default-variables" : [
        {
            "name" : "author",
            "value" : "<content encoded in Base64>"
        },
        {
            "name" : "twitter",
            "value" : "<content encoded in Base64>"
        }
    ],

    "slides" : {
      "configuration" : {
        "slides-container" : "slideshowfx-slides-div",
        "slide-id-prefix" : "slide-",
        "template-directory" : "slides/template",
        "presentation-directory" : "slides/presentation",
        "thumbnail-directory" : "slides/presentation/thumbnails"
      },
      "slides-definition" : [
        {
          "id" : 1,
          "name" : "Title",
          "file" : "title.html",
          "elements" : [
            {
              "id" : 1,
              "html-id" : "${slideNumber}-title",
              "default-content" : "Title"
            }, {
              "id" : 2,
              "html-id" : "${slideNumber}-subtitle",
              "default-content" : "Subtitle"
            }, {
               "id" : 3,
               "html-id" : "${slideNumber}-author",
               "default-content" : "Author"
            }, {
               "id" : 4,
               "html-id" : "${slideNumber}-twitter",
               "default-content" : "@Twitter"
             }
          ]
        },
        {
          "id" : 2,
          "name" : "Title and content",
          "file" : "title_content.html",
          "elements" : [
            {
              "id" : 1,
              "html-id" : "${slideNumber}-title",
              "default-content" : "Title"
            }, {
              "id" : 2,
              "html-id" : "${slideNumber}-content",
              "default-content" : "Content"
            }
          ]
        },
        {
          "id" : 3,
          "name" : "Empty",
          "file" : "empty.html",
          "elements" : [
            {
              "id" : 1,
              "html-id" : "${slideNumber}-content",
              "default-content" : "Content"
            }
          ],
          "dynamic-attributes" : [
            {
              "attribute" : "data-x",
              "template-expression" : "slideDataX",
              "prompt-message" : "Enter X position of the slide:"
            },
            {
              "attribute" : "data-y",
              "template-expression" : "slideDataY",
              "prompt-message" : "Enter Y position of the slide:"
            }
          ]
        }
      ]
    }
  }
}
----

The complete configuration is wrapped into a *template* JSON object. This object is described as below:

* *name* : the name of the template ;
* *file* : the HTML file that is the template, which will host the slides ;
* *js-object* : is the name JavaScript object that will be used to callback to SlideshowFX ;
* *slides-container* : is the ID of the HTML markup that will contain the slides ;
* *resources-directory* : the folder that will contain the resources of the presentation, typically images file, sounds, etc ;
* *default-variables* : define custom variables that can be used inside the presentation. It is not mandatory ;
** *name* : the name of the variable ;
** *value* : the value of the variable encoded in Base64 ;
* *slides* : define the configuration of slides inside the presentation, as well as their template ;
** *configuration* : JSON object that will contain the configuration of the slides ;
*** *slide-id-prefix* : is a prefix that will be placed in the ID attribute of an HTML slide element, prefixing the slide number ;
*** *template-directory* : the directory that will contain the slide’s templates ;
*** *presentation-directory* : the directory that will contain the slides of the presentation, created by the user ;
*** *thumbnail-directory* : the directory that will contain the thumbnail of each slide created by the user ;
** *slides-definition* : a JSON array that will contain the definition of each slide template as a JSON object with the following structure:
*** *id* : the ID of the slide ;
*** *name* : the name of the slide that will be displayed in SlideshowFX in the lst of available slide’s type ;
*** *file* : the template file of the slide ;
*** *elements* : a JSON array composed of JSON documents that describe all elements that can be dynamic modified (by the user or by SlideshowFX):
**** *id* : the ID for the element ;
**** *html-id* : the HTML ID of the element within the presentation. It can contain variable ;
**** *default-content* : the default content for the element ;
*** *dynamic-attributes* : a JSON array composed of JSON object describing the attributes that can be dynamically created when creating a slide by prompting its value to the user. Each object is structured as follow:
**** *attribute* : the name of the attribute ;
**** *template-expression* : the name of the template token. It is the Velocity token without the dollar sign ;
**** *prompt-message* : the message displayed to the user asking the value of the attribute.

==== Template file

The template file is the file that will host all slides, include all JavaScript libraries, CSS files and so on. In order to work, you have to:

- insert the freemarker token *$\{sfxJavascriptResources\}* inside a *script* code block
- define an ID for the HTML element that will host all slides
- insert the following JavaScript function with the right implementation for changing slides using https://www.leapmotion.com/[LeapMotion]

[source,javascript]
----
function slideshowFXLeap(keyCode) {
  // Manage the LEFT and RIGHT key codes for changing slides
}
----

- insert the JavaScript function with the right implementation returning the current slide

[source,javascript]
----
function slideshowFXGetCurrentSlide() {
  // Return the current slide
}
----

- insert the JavaScript function with the right implementation to go to a specified slide

[source,javascript]
----
function slideshowFXGotoSlide(slideId) {
  // Go to the slide identified by the given ID
}
----

- insert the JavaScript function with the right implementation to go to the next slide

[source,javascript]
----
function slideshowFXNextSlide() {
  // Go to the next slide
}
----

- insert the JavaScript function with the right implementation to go to the previous slide

[source,javascript]
----
function slideshowFXPreviousSlide() {
  // Go to the previous slide
}
----

==== Slide’s template file

The template of a slide will define what HTML element a slide is. In some frameworks it will be a *section* markup, in others a *div* and so on. In order to create a template, you will have to respect some pre-requisites:

- The slide markup must have its ID attribute set to *$\{slideIdPrefix\}$\{slideNumber}*
- Each element that is editable by the user must have an ID attribute composed of the slide number and a discriminator. An example of the title of the slide:
[source,html]
<h1 id="${slideNumber}-title"></h1>
- Each element that is editable by the user must have the *ondblclick* attribute set to *$\{sfxCallback\}*
- If dynamic attributes are needed, they can be defined like the following. Note that for this example, template-expression are *slideDataX* and *slideDataY*
[source,html]
<section ${slideDataX} ${slideDataY}></section>

==== Valid template engine tokens

The following template engine tokens are available for SlideshowFX:

* *$\{slideIdPrefix\}* indicates the prefix that will be placed before the slide number for each slide ;
* *$\{slideNumber\}* indicates the slide number generated by SlideshowFX ;
* *$\{sfxCallback\}* indicates the function that will call SlideshowFX from JavaScript ;
* *$\{sfxJavascriptResources\}* indicates the JavaScript resources SlideshowFX will insert in the presentation, like the one for inserting content, calling a quiz etc.

=== Presentations

Presentations made with SlideshowFX are an archive with the *.sfx* extension. The archive contains:

- The whole template structure
- The *presentation.html* file which is the whole presentation
- The *presentation-config.json* which is the whole configuration of the presentation

==== Configuration file

The configuration of the presentation is wrapped into an JSON configuration file named *presentation-config.json*. Here is a configuration example:
[source]
----
{
  "presentation": {
    "custom-resources": [
        {
            "type": "<type>",
            "content": "<content encoded in Base64>"
        },
        {
           "type": "<type>",
           "content": "<content encoded in Base64>"
       }
    ],
    "variables": [
        {
            "name": "author",
            "value": "<content encoded in Base64>"
        },
        {
            "name": "twitter",
            "value": "<content encoded in Base64>"
        }
    ],
    "slides": [
      {
        "template-id": 1,
        "id": "slide-1400836547234",
        "number": "1400836547234",
        "elements": [
          {
            "template-id": 3,
            "element-id": "1400836547234-author",
            "original-content-code": "HTML",
            "original-content": "<content encoded in Base64>",
            "html-content": "<content encoded in Base64>"
          },
          {
            "template-id": 4,
            "element-id": "1400836547234-twitter",
            "original-content-code": "HTML",
            "original-content": "<content encoded in Base64>",
            "html-content": "<content encoded in Base64>"
          },
          {
            "template-id": 1,
            "element-id": "1400836547234-title",
            "original-content-code": "HTML",
            "original-content": "<content encoded in Base64>",
            "html-content": "<content encoded in Base64>"
          },
          {
            "template-id": 2,
            "element-id": "1400836547234-subtitle",
            "original-content-code": "HTML",
            "original-content": "<content encoded in Base64>",
            "html-content": "<content encoded in Base64>"
          }
        ]
      },
      {
        "template-id": 2,
        "id": "slide-1400836587307",
        "number": "1400836587307",
        "elements": [
          {
            "template-id": 1,
            "element-id": "1400836587307-title",
            "original-content-code": "HTML",
            "original-content": "<content encoded in Base64>",
            "html-content": "<content encoded in Base64>"
          },
          {
            "template-id": 2,
            "element-id": "1400836587307-content",
            "original-content-code": "TEXTILE",
            "original-content": "<content encoded in Base64>",
            "html-content": "<content encoded in Base64>"
          }
        ]
      }
    ]
  }
}
----

The *presentation* JSON object is described below:

* *custom-resources* : the JSON that will contain a JSON object for each custom resource of the presentation ;
** *type* : the type of the resource. Possible values are *JAVASCRIPT_FILE*, *CSS_FILE*, *SCRIPT* and *CSS* ;
** *content* : the content of the resource encoded in Base64 ;
* *variables* : define custom variables that can be used inside the presentation. It is not mandatory ;
** *name* : the name of the variable ;
** *value* : the value of the variable encoded in Base64 ;
* *slides* : the JSON array that will contain a JSON object for each slide of the presentation ;
** *template-id* : the ID of the Slide that serves as template ;
** *id* : the ID of the slide ;
** *number* : the slide number ;
** *elements* : the array containing a JSON object for each element defined in the slide ;
*** *template-id* : the ID of the slide element in the template ;
*** *element-id* : the ID of the slide element ;
*** *original-content-code* : the code of the markup syntax used ;
*** *original-content* : the original content of the element encoded in Base64. This syntax of the content must correspond to the content code ;
*** *html-content* : the original content converted in HTML encoded in Base64.