package com.twasyl.slideshowfx.content.extension.code.enums;

/**
 * This enumeration represents languages that are supported for the Code content extension.
 *
 * @author Thierry Wasylczenko
 * @version 1.0
 * @since SlideshowFX 1.0
 */
public enum SupportedLanguage {
    ASSEMBLY_6502("6502 Assembly", "asm6502"),
    ABAP("ABAP", "abap"),
    AUGMENTED_BACKUS_NAUR_FORM("Augmented Backus-Naur form", "abnf"),
    ACTION_SCRIPT("ActionScript", "actionscript"),
    ADA("Ada", "ada"),
    AL("AL", "al"),
    ANTLR4("ANTLR4", "antlr4"),
    APACHE_CONFIGURATION("Apache configuration", "apacheconf"),
    APL("APL", "apl"),
    APPLE_SCRIPT("AppleScript", "applescript"),
    AQL("AQL", "aql"),
    ARDUINO("Arduino", "arduino"),
    ARFF("ARFF", "arff"),
    ASCIIDOC("AsciiDoc", "asciidoc"),
    ASP_NET("ASP.NET", "aspnet"),
    AUTO_IT("AutoIt", "autoit"),
    AUTO_HOTKEY("AutoHotkey", "autohotkey"),
    BACKUS_NAUR_FORM("Backus-Naur form + Routing Backus-Naur form", "bnf"),
    BASH("Bash", "bash"),
    BASIC("BASIC", "basic"),
    BATCH("Batch", "batch"),
    BBCODE("BBcode", "bbcode"),
    BISON("Bison", "bison"),
    BRAINFUCK("Brainfuck", "brainfuck"),
    BRIGHT_SCRIPT("BrightScript","brightscript"),
    BRO("Bro", "bro"),
    C("C", "c"),
    C_LIKE("C-like", "clike"),
    CIL("CIL", "cil"),
    CLOJURE("Clojure", "clojure"),
    CMAKE("CMake", "cmake"),
    COFFEE_SCRIPT("Coffee Script", "coffeescript"),
    CONCURNAS("Concurnas", "concurnas"),
    CONTENT_SECURITY_POLICY("Content-Security-Policy", "csp"),
    CPP("C++", "cpp"),
    CRYSTAL("Crystal", "crystal"),
    CSHARP("C#", "csharp"),
    CSS("CSS", "css"),
    CSS_EXTRAS("CSS Extras", "css-extras"),
    D("D", "d"),
    DART("Dart", "dart"),
    DAX("DAX", "dax"),
    DIFF("Diff", "diff"),
    DJANGO("Django/Jinja2", "django"),
    DNS_ZONE_FILE("DNS zone file", "dns-zone-file"),
    DOCKER("Docker", "docker"),
    EIFFEL("Eiffel", "eiffel"),
    EJS("EJS", "ejs"),
    ELIXIR("Elixir", "elixir"),
    ELM("Elm", "elm"),
    EMBEDDED_LUA_TEMPLATING("Embedded Lua templating", "etlua"),
    ERB("ERB", "erb"),
    ERLANG("Erlang", "erlang"),
    EXCEL_FORMULA("Excel Formula", "excel-formula"),
    EXTENDED_BACKUS("Extended Backus-Naur form", "ebnf"),
    FACTOR("Factor", "factor"),
    FIRESTORE_SECURITY_RULES("Firestore security rules", "firestore-security-rules"),
    FLOW("Flow", "flow"),
    FORTRAN("Fortran", "fortran"),
    FREEMARKER_TEMPLATE_LANGUAGE("FreeMarker Template Language", "ftl"),
    FSHARP("F#", "fsharp"),
    G_CODE("G-code", "gcode"),
    GAMEMAKER_LANGUAGE("GameMaker Language", "gamemakerlanguage"),
    GDSCRIPT("GDScript", "gdscript"),
    GEDCOM("GEDCOM", "gedcom"),
    GHERKIN("Gherkin", "gherkin"),
    GIT("git", "git"),
    GLSL("GLSL", "glsl"),
    GO("Go", "go"),
    GRAPH_QL("GraphQL", "graphql"),
    GROOVY("Groovy", "groovy"),
    HAML("Haml", "haml"),
    HANDLEBARS("Handlebars", "handlebars"),
    HASKELL("Haskell", "haskell"),
    HAXE("Haxe", "haxe"),
    HCL("HCL", "hcl"),
    HLSL("HLSL", "hlsl"),
    HTML("HTML", "html"),
    HTTP("HTTP", "http"),
    HTTP_PUBLIC_KEY_PINS("HTTP Public-Key-Pins", "hpkp"),
    HTTP_STRICT_TRANSPORT_SECURITY("HTTP Strict-Transport-Security", "hsts"),
    ICHIGOJAM("IchigoJam", "ichigojam"),
    ICON("Icon", "icon"),
    INFORM_7("Inform 7", "inform"),
    INI("Ini", "ini"),
    IO("Io", "io"),
    J("J", "j"),
    JAVA("Java", "java"),
    JAVADOC("JavaDoc", "javadoc"),
    JAVADOC_LIKE("JavaDoc-like", "javadoclike"),
    JAVA_STACK_TRACE("Java stack trace", "javastacktrace"),
    JAVASCRIPT("JavaScript", "javascript"),
    JOLIE("Jolie", "jolie"),
    JQ("JQ", "jq"),
    JS_EXTRAS("JS Extras", "js-extras"),
    JS_TEMPLATES("JS Templates", "js-templates"),
    JSDOC("JSDoc", "jsdoc"),
    JSON("JSON", "json"),
    JSON5("JSON5", "json5"),
    JSONP("JSONP", "jsonp"),
    JULIA("Julia", "julia"),
    KEYMAN("Keyman", "keyman"),
    KOTLIN("Kotlin", "kotlin"),
    LATEX("LateX", "latex"),
    LATTE("Latte", "latte"),
    LESS("Less", "less"),
    LILYPOND("LilyPond", "lilypond"),
    LIQUID("Liguid", "liquid"),
    LISP("Lisp", "lisp"),
    LIVE_SCRIPT("LiveScript", "livescript"),
    LLVM_IR("LLVM IR", "llvm"),
    LOLCODE("LOLCODE", "lolcode"),
    LUA("Lua", "lua"),
    MAKEFILE("Makefile", "makefile"),
    MARKDOWN("Markdown", "markdown"),
    MARKUP("Markup", "markup"),
    MARKUP_TEMPLATING("Markup templating", "markup-templating"),
    MATLAB("MATLAB", "matlab"),
    MEL("MEL", "mel"),
    MIZAR("Mizar", "mizar"),
    MONKEY("Monkey", "monkey"),
    MOONSCRIPT("MoonScript", "moonscript"),
    N1QL("N1QL", "n1ql"),
    N4JS("N4JS", "n4js"),
    NAND_TO_TETRIS_HDL("Nand To Tetris HDL", "nand2tetris-hdl"),
    NASM("NASM", "nasm"),
    NEON("NEON", "neon"),
    NGINX("nginx", "nginx"),
    NIM("Nim", "nim"),
    NIX("Nix", "nix"),
    NSIS("NSIS", "nsis"),
    OBJECTIVE_C("Objective-C", "objectivec"),
    OCAML("OCaml", "ocaml"),
    OPENCL("OpenCL", "opencl"),
    OZ("Oz", "oz"),
    PARI_GP("PARI/GP", "parigp"),
    PARSER("Parser", "parser"),
    PASCAL("Pascal", "pascal"),
    PASCALIGO("Pascaligo", "pascaligo"),
    PC_AXIS("PC-Axis", "pcaxis"),
    PEOPLECODE("PeopleCode", "peoplecode"),
    PERL("Perl", "perl"),
    PHP("PHP", "php"),
    PHPDOC("PHPDoc", "phpdoc"),
    PHP_EXTRAS("PHP Extras", "php-extras"),
    PL_SQL("PL/SQL", "plsql"),
    POWER_QUERY("PowerQuery", "powerquery"),
    POWER_SHELL("PowerShell", "powershell"),
    PROCESSING("Processing", "processing"),
    PROLOG("Prolog", "prolog"),
    PROPERTIES(".properties", "properties"),
    PROTOCOL_BUFFERS("Protocol Buffers", "protobuf"),
    PUG("Pug", "pug"),
    PUPPET("Puppet", "puppet"),
    PURE("Pure", "pure"),
    PURE_BASIC("PureBasic", "purebasic"),
    PYTHON("Python", "python"),
    Q("Q", "q"),
    QML("QML", "qml"),
    QORE("Qore", "qore"),
    R("R", "r"),
    RACKET("Racket", "racket"),
    REACT_JSX("React JSX", "jsx"),
    REACT_TSX("React TSX", "tsx"),
    RENPY("Ren'py", "renpy"),
    REASON("Reason", "reason"),
    REGEX("Regex", "regex"),
    REST("reST", "rest"),
    RIP("Rip", "rip"),
    ROBOCONF("Roboconf", "roboconf"),
    ROBOT_FRAMEWORK("Robot Framework", "robotframework"),
    RUBY("Ruby", "ruby"),
    RUST("Rust", "rust"),
    SAS("SAS", "sas"),
    SASS_SASS("Saas (Sass)", "sass"),
    SASS_SCSS("Sass (Scss)", "scss"),
    SCALA("Scala", "scala"),
    SCHEME("Scheme", "scheme"),
    SHELL_SESSION("Shell session", "shell-session"),
    SMALLTALK("Smalltalk", "smalltalk"),
    SMARTY("Smarty", "smarty"),
    SQL("SQL", "sql"),
    SOLIDITY("Solidity (Ethereum)", "solidity"),
    SOLUTION_FILE("Solution file", "solution-file"),
    SOY("Soy (Closure Template)", "soy"),
    SPARQL("SPARQL", "sparql"),
    SPLUNK_SPL("Splunk SPL", "splunk-spl"),
    SQF("SQF: Status Quo Function (Arma 3)", "sqf"),
    STRUCTURED_TEXT("Structured Text (IEC 61131-3)", "iecst"),
    STYLUS("Stylus", "stylus"),
    SWIFT("Swift", "swift"),
    T4_TEMPLATING("T4 templating", "t4-templating"),
    T4_TEMPLATING_CSHARP("T4 templating (C#)", "t4-cs"),
    T4_TEMPLATING_VB("T4 templating (VB)", "t4-vb"),
    TAP("TAP", "tap"),
    TCL("Tcl", "tcl"),
    TEXTILE("Textile", "textile"),
    TEMPLATE_TOOLKIT_2("Template Toolkit 2","tt2"),
    TOML("TOML", "toml"),
    TWIG("Twig", "twig"),
    TYPE_SCRIPT("TypeScript", "typescript"),
    UNREALSCRIPT("UnrealScript", "unrealscript"),
    VALA("Vala", "vala"),
    VB_NET("VB.NET", "vbnet"),
    VELOCITY("Velocity", "velocity"),
    VERILOG("Verilog", "verilog"),
    VHDL("VHDL", "vhdl"),
    VIM("vim", "vim"),
    VISUAL_BASIC("Visual Basic", "visual-basic"),
    WARPSCRIPT("WarpScript", "warpscript"),
    WEB_ASSEMBLY("WebAssembly", "wasm"),
    WIKI("Wiki markup", "wiki"),
    XEORA("Xeora", "xeora"),
    XML_DOC("XML doc (.net)", "xml-doc"),
    XOJO("Xojo (REALbasic)", "xojo"),
    XQUERY("XQuery", "xquery"),
    YAML("YAML", "yaml"),
    ZIG("Zig", "zig");

    private static final String CSS_PREFIX = "language-";
    private String name;
    private String cssClass;

    SupportedLanguage(String name, String cssClass) {
        this.name = name;
        this.cssClass = CSS_PREFIX.concat(cssClass);
    }

    /**
     * Get the name of the {@link SupportedLanguage}. This name could be displayed in a UI.
     *
     * @return The name of the supported language.
     */
    public String getName() {
        return name;
    }

    /**
     * Get the CSS class associated to this {@link SupportedLanguage}.
     *
     * @return The CSS class of this supported language.
     */
    public String getCssClass() {
        return cssClass;
    }

    public static SupportedLanguage fromName(String name) {
        SupportedLanguage sl = null;

        for (SupportedLanguage s : SupportedLanguage.values()) {
            if (s.getName().equals(name)) {
                sl = s;
                break;
            }
        }

        return sl;
    }
}
