name: CI
on:
  push:
    paths:
      - .github/workflows/*.py

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OS_NAME: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Test CI script
        run: python .github/workflows/test_ci.py